```{r}

library(dplyr)
library(xgboost)
library(OptimalCutpoints)
library(caret)
library(SHAPforxgboost)
#source("a_insights_shap_functions.r")
library(ggplot2)
library(parallel)
#library(xgboostExplainer)

library(foreach)
library(doParallel)

```


```{r}
load("PredictionData-4.RData")
```

```{r}
#Create weighted 80/20 split
set.seed(42)
train.index <- createDataPartition(PredictionData4$OT, p = .8, list = FALSE)
train_db <- PredictionData4[ train.index,]
test_db  <- PredictionData4[-train.index,]

summary(as.factor(train_db$OT))
summary(as.factor(test_db$OT))
```








```{r}
train_db <- train_db %>% select(-GameKey, -Season, -AwayTeam, -HomeTeam, -AwayGameNumber, -HomeGameNumber, -Date) 

test_db <- test_db %>% select(-GameKey, -Season, -AwayTeam, -HomeTeam, -AwayGameNumber, -HomeGameNumber, -Date) 
```

#### Preparing for XGBoost
```{r}
dtrain <- xgb.DMatrix(data = as.matrix(train_db %>% select(-OT)), label = train_db$OT)
dtest <- xgb.DMatrix(data = as.matrix(test_db %>% select(-OT)), label = test_db$OT)
```




#Parameter Tuning grid search

```{r}
tuning_grid <- expand.grid(
    eta = c(0.1, 0.05, 0.3)
  , scale_pos_weight = c(1, 5, 7, 10)
  #, nrounds = seq(100, 1000, by = 50)
  , max_depth_vals = c(5, 7, 20)
  , min_child_weight = c(1, 10, 20)
  , gamma_vals = c(0, 0.05, 0.1, 0.2)
  , subsample = c(0.5, 0.75, 1)
  , colsample_by_tree = c(0.5, 0.75, 1)
  
)
```


Using foreach
```{r}


start.time <- Sys.time()

cl <- makeCluster(12) #number of cores

registerDoParallel(cl)

ParametersResults <- foreach(i = 1:nrow(tuning_grid), .combine = "rbind", .packages = c("xgboost", "dplyr")) %dopar%  {
  
  dtrain <- xgb.DMatrix(data = as.matrix(train_db %>% select(-OT)), label = train_db$OT)
  
  set.seed(42)
bst_mod <- xgb.cv(data = dtrain, # Set training data
              
              nfold = 5, # Use 5 fold cross-validation
               
              eta = tuning_grid[i,]$eta, # Set learning rate
              max.depth = tuning_grid[i,]$max_depth_vals, # Set max depth
              min_child_weight = tuning_grid[i,]$min_child_weight, # Set minimum number of samples in node to split
              gamma = tuning_grid[i,]$gamma_vals, # Set minimum loss reduction for split
              subsample = tuning_grid[i,]$subsample, # Set proportion of training data to use in tree
              colsample_bytree =  tuning_grid[i,]$colsample_by_tree, # Set number of variables to use in each tree
              
              scale_pos_weight = tuning_grid[i,]$scale_pos_weight,
               
              nrounds = 1500, # Set number of rounds
              #early_stopping_rounds = 200, # Set number of rounds to stop at if there is no improvement
               
              verbose = 0, # 1 - Prints out fit
              nthread = 1, # Set number of parallel threads
             # print_every_n = 100, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              #,eval_metric = "error" # Set evaluation metric to use
)
  
  

aucpr_max <- max(bst_mod$evaluation_log$test_aucpr_mean)

round_aucpr_max <- match(aucpr_max, bst_mod$evaluation_log$test_aucpr_mean)

#error_of_max_auc <- bst_mod$evaluation_log$test_error_mean[round_aucpr_max]

#error_min <- min(bst_mod$evaluation_log$test_error_mean)

#round_error_min <- match(error_min, bst_mod$evaluation_log$test_error_mean)

#auc_of_min_error <- bst_mod$evaluation_log$test_auc_mean[round_error_min]


data.frame(tuning_grid[i,], aucpr_max, round_aucpr_max)#, error_of_max_auc, error_min, round_error_min, auc_of_min_error)



}


stopCluster(cl)


end.time <- Sys.time()
time.taken <- end.time - start.time

save(ParametersResults, file = "ParametersResults4.RData")
```


```{r}
time.taken
```
Best Option from prior data version
```{r}
set.seed(42)
bst_final_3 <- xgboost(data = dtrain, # Set training data
              
      
              eta = 0.1, # Set learning rate
              max.depth = 7, # Set max depth
              min_child_weight = 20, # Set minimum number of samples in node to split
              gamma = 0.10, # Set minimum loss reduction for split
              subsample = 0.5, # Set proportion of training data to use in tree
              colsample_bytree =  1.0, # Set number of variables to use in each tree
              
              scale_pos_weight = 7,
               
              nrounds = 4, # Set number of rounds
              #early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
              verbose = 1, # 1 - Prints out fit
              nthread = 2, # Set number of parallel threads
              print_every_n = 20, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              ) # Set evaluation metric to use
```

```{r}
boost_preds <- predict(bst_final_3, dtrain) # Create predictions for xgboost model
# Join predictions and actual
pred_dat <- cbind.data.frame(boost_preds , train_db$OT)
names(pred_dat) <- c("predictions", "response")
oc<- optimal.cutpoints(X = "predictions",
                       status = "response",
                       tag.healthy = 0,
                       data = pred_dat,
                       methods = "MaxProdNPVPPV")

boost_preds_3 <- predict(bst_final_3, dtest) # Create predictions for xgboost model

pred_dat <- cbind.data.frame(boost_preds_3 , test_db$OT)#
# Convert predictions to classes, using optimal cut-off
boost_pred_class_3<- rep(0, length(boost_preds_3))
#boost_pred_class_3[boost_preds_3 >= oc$MaxProdNPVPPV$Global$optimal.cutoff$cutoff[1]] <- 1

boost_pred_class_3[boost_preds_3 >= .5681] <- 1

t_3 <- table(boost_pred_class_3, actual = test_db$OT) # Create table
confusionMatrix(t_3, positive = "1") # Produce confusion matrix
```



```{r}
summary(boost_preds_3)

Q3_cuttoff <- summary(boost_preds_3)[[5]]


PosPredValue <- confusionMatrix(t_3, positive = "1")$byClass[["Pos Pred Value"]]
```



```{r}
ParametersResults_arrange <- ParametersResults %>% arrange(desc(aucpr_max))
```


```{r}
start.time <- Sys.time()

cl <- makeCluster(12) #number of cores

registerDoParallel(cl)

TrainingResults <- foreach(i = 1:nrow(ParametersResults_arrange), .combine = "rbind", .packages = c("xgboost", "dplyr", "caret")) %dopar%  {
  
  
  set.seed(42)
  dtrain <- xgb.DMatrix(data = as.matrix(train_db %>% select(-OT)), label = train_db$OT)
  dtest <- xgb.DMatrix(data = as.matrix(test_db %>% select(-OT)), label = test_db$OT)
  
  
  set.seed(42)
  bst_final <- xgboost(data = dtrain, # Set training data
              
     
              eta = ParametersResults_arrange$eta[i] , # Set learning rate
              max.depth = ParametersResults_arrange$max_depth_vals[i], # Set max depth
              min_child_weight = ParametersResults_arrange$min_child_weight[i], # Set minimum number of samples in node to split
              gamma = ParametersResults_arrange$gamma_vals[i], # Set minimum loss reduction for split
              subsample = ParametersResults_arrange$subsample[i], # Set proportion of training data to use in tree
              colsample_bytree =  ParametersResults_arrange$colsample_by_tree[i], # Set number of variables to use in each tree
              
              scale_pos_weight = ParametersResults_arrange$scale_pos_weight[i],
               
              nrounds = ParametersResults_arrange$round_aucpr_max[i], # Set number of rounds
              #early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
              verbose = 0, # 1 - Prints out fit
              nthread = 1, # Set number of parallel threads
              #print_every_n = 20, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              ) # Set evaluation metric to use
  
  
 boost_preds <- predict(bst_final, dtest) # Create predictions for xgboost model

  pred_dat <- cbind.data.frame(boost_preds , test_db$OT)#
  # Convert predictions to classes, using optimal cut-off
  boost_pred_class<- rep(0, length(boost_preds))
  #boost_pred_class_3[boost_preds_3 >= oc$MaxProdNPVPPV$Global$optimal.cutoff$cutoff[1]] <- 1

  Q3_cuttoff <- summary(boost_preds)[[5]] #Calling Q3 cuttoff the ones to make positive
  
  boost_pred_class[boost_preds >= Q3_cuttoff] <- 1

  t <- table(boost_pred_class, actual = test_db$OT) # Create table
  PosPredValue <- confusionMatrix(t, positive = "1")$byClass[["Pos Pred Value"]] 
  
  
  data.frame(ParametersResults_arrange[i,], Q3_cuttoff, PosPredValue)#, error_of_max_auc, error_min, round_error_min, auc_of_min_error)



}


stopCluster(cl)


end.time <- Sys.time()
time.taken <- end.time - start.time

save(TrainingResults, file = "TrainingResults.RData")
  
```

```{r}
time.taken
```

Looking at best result
```{r}
set.seed(42)
bst_best <- xgboost(data = dtrain, # Set training data
              
      
              eta = 0.1, # Set learning rate
              max.depth = 20, # Set max depth
              min_child_weight = 1, # Set minimum number of samples in node to split
              gamma = 0.05, # Set minimum loss reduction for split
              subsample = 0.75, # Set proportion of training data to use in tree
              colsample_bytree =  0.75, # Set number of variables to use in each tree
              
              scale_pos_weight = 5,
               
              nrounds = 22, # Set number of rounds
              #early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
              verbose = 1, # 1 - Prints out fit
              nthread = 2, # Set number of parallel threads
              print_every_n = 20, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              ) # Set evaluation metric to use
```

```{r}
boost_preds <- predict(bst_best, dtest) # Create predictions for xgboost model

  pred_dat <- cbind.data.frame(boost_preds , test_db$OT)#
  # Convert predictions to classes, using optimal cut-off
  boost_pred_class<- rep(0, length(boost_preds))
  #boost_pred_class_3[boost_preds_3 >= oc$MaxProdNPVPPV$Global$optimal.cutoff$cutoff[1]] <- 1

  Q3_cuttoff <- summary(boost_preds)[[5]] #Calling Q3 cuttoff the ones to make positive
  
  #boost_pred_class[boost_preds >= Q3_cuttoff] <- 1
  
  boost_pred_class[boost_preds >= 0.55] <- 1

  t <- table(boost_pred_class, actual = test_db$OT) # Create table
  PosPredValue <- confusionMatrix(t, positive = "1")$byClass[["Pos Pred Value"]]
  confusionMatrix(t, positive = "1") # Produce confusion matrix
```

```{r}
summary(boost_preds)
```













Test with 2024-2025 Data
```{r}
load("C:/Users/dmich/Documents/Hockey Prediction/OT Prediction/Scrape 2024-2025 Data/Clean2024_2025_Data_3.RData")
```


```{r}

Predict_Data <- Clean2024_2025_Data_3 %>% select(-GameKey, -Season, -AwayTeam, -HomeTeam, -AwayGameNumber, -HomeGameNumber, -Date) 

dpredict <- xgb.DMatrix(data = as.matrix(Predict_Data %>% select(-OT)), label = Predict_Data$OT)

cutoffvalue <- Q3_cuttoff

```

```{r}


boost_preds <- predict(bst_best, dpredict) # Create predictions for xgboost model
# Join predictions and actual
pred_dat <- cbind.data.frame(boost_preds , Predict_Data$OT)
names(pred_dat) <- c("predictions", "response")

#oc<- optimal.cutpoints(X = "predictions",
#                       status = "response",
#                       tag.healthy = 0,
#                       data = pred_dat,
#                       methods = "MaxEfficiency")

#boost_preds_MaxAUC <- predict(bst_final_MaxAUC, dtest) # Create predictions for xgboost model

#pred_dat <- cbind.data.frame(boost_preds_MaxAUC , test_db$OT)#
# Convert predictions to classes, using optimal cut-off
boost_pred_class <- rep(0, length(boost_preds))

#boost_pred_class[boost_preds >= cutoffvalue] <- 1
#0.5400651
boost_pred_class[boost_preds >= .43] <- 1


t <- table(boost_pred_class, actual = Predict_Data$OT) # Create table
confusionMatrix(t, positive = "1") # Produce confusion matrix
```


```{r}
load("C:/Users/dmich/Documents/Hockey Prediction/OT Prediction/Scrape 2024-2025 Data/Clean2024_2025_Data_3.RData")
```


```{r}

Predict_Data <- Clean2024_2025_Data_3 %>% select(-GameKey, -Season, -AwayTeam, -HomeTeam, -AwayGameNumber, -HomeGameNumber, -Date) 

dpredict <- xgb.DMatrix(data = as.matrix(Predict_Data %>% select(-OT)), label = Predict_Data$OT)

cutoffvalue <- Q3_cuttoff

```


```{r}
start.time <- Sys.time()

cl <- makeCluster(12) #number of cores

registerDoParallel(cl)

TrainingResults <- foreach(i = 1:nrow(ParametersResults_arrange), .combine = "rbind", .packages = c("xgboost", "dplyr", "caret")) %dopar%  {
  
  
  set.seed(42)
  dtrain <- xgb.DMatrix(data = as.matrix(train_db %>% select(-OT)), label = train_db$OT)
  dtest <- xgb.DMatrix(data = as.matrix(test_db %>% select(-OT)), label = test_db$OT)
  
  
  set.seed(42)
  bst_final <- xgboost(data = dtrain, # Set training data
              
     
              eta = ParametersResults_arrange$eta[i] , # Set learning rate
              max.depth = ParametersResults_arrange$max_depth_vals[i], # Set max depth
              min_child_weight = ParametersResults_arrange$min_child_weight[i], # Set minimum number of samples in node to split
              gamma = ParametersResults_arrange$gamma_vals[i], # Set minimum loss reduction for split
              subsample = ParametersResults_arrange$subsample[i], # Set proportion of training data to use in tree
              colsample_bytree =  ParametersResults_arrange$colsample_by_tree[i], # Set number of variables to use in each tree
              
              scale_pos_weight = ParametersResults_arrange$scale_pos_weight[i],
               
              nrounds = ParametersResults_arrange$round_aucpr_max[i], # Set number of rounds
              #early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
              verbose = 0, # 1 - Prints out fit
              nthread = 1, # Set number of parallel threads
              #print_every_n = 20, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              ) # Set evaluation metric to use
  
  
 boost_preds <- predict(bst_final, dtest) # Create predictions for xgboost model

  pred_dat <- cbind.data.frame(boost_preds , test_db$OT)#
  # Convert predictions to classes, using optimal cut-off
  boost_pred_class<- rep(0, length(boost_preds))
  #boost_pred_class_3[boost_preds_3 >= oc$MaxProdNPVPPV$Global$optimal.cutoff$cutoff[1]] <- 1

  Q3_cuttoff <- summary(boost_preds)[[5]] #Calling Q3 cuttoff the ones to make positive
  
  boost_pred_class[boost_preds >= Q3_cuttoff] <- 1

  t <- table(boost_pred_class, actual = test_db$OT) # Create table
  PosPredValue <- confusionMatrix(t, positive = "1")$byClass[["Pos Pred Value"]] 
  
  
  
  
   #pred with 2024-2025 data
  dpredict <- xgb.DMatrix(data = as.matrix(Predict_Data %>% select(-OT)), label = Predict_Data$OT)

  cutoffvalue <- Q3_cuttoff
  
  
  boost_preds_2425 <- predict(bst_final, dpredict) # Create predictions for xgboost model
# Join predictions and actual
  pred_dat_2425 <- cbind.data.frame(boost_preds_2425 , Predict_Data$OT)
  names(pred_dat_2425) <- c("predictions", "response")


  boost_pred_class_2425 <- rep(0, length(boost_preds_2425))

  boost_pred_class_2425[boost_preds_2425 >= cutoffvalue] <- 1
  
  t2425 <- table(boost_pred_class_2425, actual = Predict_Data$OT) # Create table
  PosPredValue_2425 <- confusionMatrix(t2425, positive = "1")$byClass[["Pos Pred Value"]]
  
  
  
  
  
  data.frame(ParametersResults_arrange[i,], Q3_cuttoff, PosPredValue, PosPredValue_2425)#, error_of_max_auc, error_min, round_error_min, auc_of_min_error)



}


stopCluster(cl)


end.time <- Sys.time()
time.taken <- end.time - start.time

save(TrainingResults, file = "TrainingResults.RData")
  
```

```{r}
time.taken
```

```{r}
set.seed(42)
bst_best <- xgboost(data = dtrain, # Set training data
              
      
              eta = 0.1, # Set learning rate
              max.depth = 20, # Set max depth
              min_child_weight = 1, # Set minimum number of samples in node to split
              gamma = 0.05, # Set minimum loss reduction for split
              subsample = 1.00, # Set proportion of training data to use in tree
              colsample_bytree =  0.75, # Set number of variables to use in each tree
              
              scale_pos_weight = 7,
               
              nrounds = 19, # Set number of rounds
              #early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
              verbose = 1, # 1 - Prints out fit
              nthread = 2, # Set number of parallel threads
              print_every_n = 20, # Prints out result every 20th iteration
              
              objective = "binary:logistic", # Set objective
              eval_metric = "aucpr"
              ) # Set evaluation metric to use
```
```{r}
boost_preds <- predict(bst_best, dtest) # Create predictions for xgboost model

  pred_dat <- cbind.data.frame(boost_preds , test_db$OT)#
  # Convert predictions to classes, using optimal cut-off
  boost_pred_class<- rep(0, length(boost_preds))
  #boost_pred_class_3[boost_preds_3 >= oc$MaxProdNPVPPV$Global$optimal.cutoff$cutoff[1]] <- 1

  Q3_cuttoff <- summary(boost_preds)[[5]] #Calling Q3 cuttoff the ones to make positive
  
  #boost_pred_class[boost_preds >= Q3_cuttoff] <- 1
  
  boost_pred_class[boost_preds >= 0.5] <- 1

  t <- table(boost_pred_class, actual = test_db$OT) # Create table
  PosPredValue <- confusionMatrix(t, positive = "1")$byClass[["Pos Pred Value"]]
  confusionMatrix(t, positive = "1") # Produce confusion matrix
```



```{r}


boost_preds <- predict(bst_best, dpredict) # Create predictions for xgboost model
# Join predictions and actual
pred_dat <- cbind.data.frame(boost_preds , Predict_Data$OT)
names(pred_dat) <- c("predictions", "response")

#oc<- optimal.cutpoints(X = "predictions",
#                       status = "response",
#                       tag.healthy = 0,
#                       data = pred_dat,
#                       methods = "MaxEfficiency")

#boost_preds_MaxAUC <- predict(bst_final_MaxAUC, dtest) # Create predictions for xgboost model

#pred_dat <- cbind.data.frame(boost_preds_MaxAUC , test_db$OT)#
# Convert predictions to classes, using optimal cut-off
boost_pred_class <- rep(0, length(boost_preds))

#boost_pred_class[boost_preds >= cutoffvalue] <- 1
#0.5400651
boost_pred_class[boost_preds >= 0.5] <- 1


t <- table(boost_pred_class, actual = Predict_Data$OT) # Create table
confusionMatrix(t, positive = "1") # Produce confusion matrix
```
